name: 'Terraform destroy'

on:
  push:
    branches:
      - main
      
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
 

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.AWS_ROLE_TO_ASSUME}}
          aws-region: us-east-1
          audience: sts.amazonaws.com  

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform destroy
        working-directory: ./terraform
        run: terraform destroy
